### ISSUE TITLE
Nix builds have no /usr/bin/env

### ISSUE THREAD

**Issue by peti** [utdemir/handsy#5]
The Cabal file doesn not declare `md5sum` as a built tool for the test suite, so our build environment does not include that path in the `chroot` set-up for the build. This causes the test to fail:

```
running tests
Running 1 test suites...
Test suite tests: RUNNING...
cat ["/bin/sh"]
handsy
  writeFile . readFile == id: mktemp []
dd ["of=/tmp/nix-build-haskell-handsy-0.0.8.drv-0/tmp.OJ0wqwifMW"]
md5sum ["/bin/sh"]
md5sum ["/tmp/nix-build-haskell-handsy-0.0.8.drv-0/tmp.OJ0wqwifMW"]
OK (0.02s)
  shell:                      md5sum ["/bin/sh"]
/usr/bin/env ["sh","-c","cat /bin/sh | md5sum -"]
FAIL
    Exception: /usr/bin/env: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

1 out of 2 tests failed (0.02s)
Test suite tests: FAIL
```

**Comment by peti** [comment]
Hmm, after some further experimentation, the issue seems to be even one level below what I assumed: the path `/usr/bin/env` does not exist! This is going to be hard to work around. Programs that ship hard-coded paths are notoriously unreliable on NixOS, because the whole `/usr` hierarchy just don't exist on our system. `/bin/sh` is the only global path we provide (and even that path shouldn't be used, really). The paths to those tools should be discovered at configure time (which would give you `/nix/store/4pxkkjjvf4fsbc2c763hlh1gn0jhmaja-bash-4.3-p30/bin/sh`), of they should be called without any path at all so that `$PATH` can find them.

Anyway, it might be nice to extend your code so that it _tests_ whether paths like `/usr/bin/env` exist or not, and maybe adapt to the situation depending on the outcome of those tests.

**Comment by utdemir** [comment]
Sorry about that!

I was running tests with

```
nix-shell --pure --command "cabal configure && cabal build -j && cabal test"
```

And assumed hydra would be happy with it.

I used the hard-coded paths just for convenience, On tests, just needed a binary file and `/bin/sh` looked easiest. I'll modify the tests not to depend on any hardcoded path. Also, I was using `/usr/bin/env sh` for spawning shell, now I'll just use `sh`, after that it should compile.

But I think I can trust `md5sum` being there, can't I? I'm assuming it comes with `stdenv` package which is included by default?

**Comment by utdemir** [comment]
0.0.9 is out on Hackage, so I'm closing the issue.
